<?php

namespace ContainerJvfhecF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetCurrencyRatesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GetCurrencyRatesCommand' shared autowired service.
     *
     * @return \App\Command\GetCurrencyRatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GetCurrencyRatesCommand.php';

        $container->privates['App\\Command\\GetCurrencyRatesCommand'] = $instance = new \App\Command\GetCurrencyRatesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CurrencyRepository'] ?? $container->load('getCurrencyRepositoryService')));

        $instance->setName('get-currency-rates');
        $instance->setDescription('Get currencies');

        return $instance;
    }
}
