<?php

namespace ContainerNURCNw1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetCurrencyRatesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GetCurrencyRatesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GetCurrencyRatesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('get-currency-rates', [], 'Get currencies', false, #[\Closure(name: 'App\\Command\\GetCurrencyRatesCommand')] fn (): \App\Command\GetCurrencyRatesCommand => ($container->privates['App\\Command\\GetCurrencyRatesCommand'] ?? $container->load('getGetCurrencyRatesCommandService')));
    }
}
